name: Deploy Lambda Function

on:
  push:
    paths:
      - "**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Install Requirements
        run: |
          pip install --platform manylinux2014_x86_64 -t package --only-binary=:all: --python-version 3.12 -r requirements.txt
      - name: Create zip for lambda function
        run: |
          (cd package; zip ../aws_lambda_artifact.zip -r .; cd ..)
          zip aws_lambda_artifact.zip -u main.py api.py sicumon/*
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:eu-west-3:442533761763:function:sicumonbackend \
            --zip-file fileb://aws_lambda_artifact.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-3"